scraf/activos/urls.py
from django.urls import path
from activos.views import (ListaActivos, RegistroActivo, RegistroActivoResponsable, VerActivo, ActualizarActivoResponsable, 
                                                ajax_r_activo, ajax_r_activo_responsable, get_auxiliares_por_grupo,
                                                LineActivo, gestionar_activo )
from activos.views_b import (ListaGruposContables, CargaContableView, ListaAuxiliatesContables, verAuxiliares, CargaDirectaActivosView,
                                                    )
app_name = 'activos'

urlpatterns = [
    #ListaActivos
    path('listaActivos/', ListaActivos.as_view(), name='lista_activos'),
    path('registroActivo/', RegistroActivo.as_view(), name='registro_activos'),

    path('registroActivoResponsable/', RegistroActivoResponsable.as_view(), name='registro_activos_responsable'),
    path('VerActivoResponsable/<slug:slug>', VerActivo.as_view(), name='ver_activos_responsable'),
    path('ActualizacionActivoResponsable/<slug:slug>', ActualizarActivoResponsable.as_view(), name='actualizar_activos_responsable'),
    path('ajax/registro/', ajax_r_activo, name='ajax_r_activo'),
    path('ajax/registro_con_responsable/', ajax_r_activo_responsable, name='ajax_r_activo_resp'),
    #Grupos Contables y Auxiliares
    path('listaGrupoContable/', ListaGruposContables.as_view(), name='lista_GrupoContable'),
    path('listaAuxiliaresContable/', ListaAuxiliatesContables.as_view(), name='lista_AuxiliaresContable'),
    path('CargarInf/', CargaContableView.as_view(), name='cargarInformacion'),
    path('verGrupoAux/<int:pk>/', verAuxiliares.as_view(), name='ver_grupoAux'),
    path('get-auxiliares/', get_auxiliares_por_grupo, name='Auxiliares_por_grupo'),
    path('listaLine/<slug:codigo>', LineActivo.as_view(), name='lista_lineactivo'),
    #actualizarDatos
    path('verActivo/<slug:codigo>/', VerActivo.as_view(), name='ver_activo'),
    path('gestionar-activo/<slug:activo_codigo>/', gestionar_activo, name='gestionar_activo'),
    #RegistomasivoActivos
    path('CargarActivos/', CargaDirectaActivosView.as_view(), name='cargaMasivaActivos'),
]

scraf/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('select2/', include('django_select2.urls')),
    path('',include('inicio.urls')),
    path('users/',include('users.urls')),
    path('revision/',include('revision.urls')),
    path('activos/',include('activos.urls')),
    path('asigdev/',include('designacion.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scraf/designacion/urls.py
from django.urls import path

from designacion.views import (ListaAsignaciones, crear_asignacion, crear_devolucion, get_activos_asignacion,confirmar_ubicacion, 
                               verAsignaciones, verDevolucion, ListaAsignacionesPersona, ListaAsignacionesPersonal,
                               Line_Asignaciones)

app_name = 'designacion'
urlpatterns = [
    path('listaActivos/', ListaAsignaciones.as_view(), name='lista_asignaciones'),
    path('listaActivosPersona/', ListaAsignacionesPersona.as_view(), name='lista_asignaciones_persona'),
    path('RegistroAsign/', crear_asignacion, name='registrar_asig'),
    path('DevolverAsign/', crear_devolucion, name='devolver_asig'),
    path('DevolverAsign/get-activos/', get_activos_asignacion, name='devolver_asig_get'),
    path('ConfirmacionUbicacion/<str:tipo>/<str:slug>/', confirmar_ubicacion, name='confirmacionUbicacion'),
    path('verAsignacion/<slug:slug>', verAsignaciones.as_view(), name='ver_asignaciones'),
    path('verDevolucion/<slug:slug>', verDevolucion.as_view(), name='ver_devolucion'),

    path('listaAsignacionesPersonal/<int:carnet>/', ListaAsignacionesPersonal.as_view(), name='lista_asignaciones_personaL'),
    path('lineAsignaciones/<slug:slug>', Line_Asignaciones.as_view(), name='line_asignaciones'),

]

scraf/revision/urls.py
from django.urls import path
from revision.views import (ListaRevisiones, ListaCambiosRevision, Revision_RActivos,
                            ajax_r_Revision, ajax_editar_revision, inicio_fin_Revision,ajax_ver_revision,
                            buscar_activo, actualizar_activo,RegistroRevisionActivoView, Comparacion)
from revision.views2 import Revision_ActivosObservados, buscar_activo_obs, actualizar_activo_obs

app_name = 'revision'
urlpatterns = [ 
    path('listaRevisiones/<slug:slug>/', ListaCambiosRevision.as_view(), name='lista_revisiones_line'),
    path('listaRevisiones/', ListaRevisiones.as_view(), name='lista_revisiones'),
    path('RevisionActivo/<slug:slug>/', Revision_RActivos.as_view(), name='revision_activo'),
    path('ajax/R_revision/', ajax_r_Revision, name='ajax_r_Revision'),
    path('ajax/A_revision/<slug:slug>/', ajax_editar_revision, name='ajax_a_Revision'),
    path('inicio-fin/<slug:slug>/', inicio_fin_Revision, name='inicio_fin_revision'),
    path('ajax/Ver_revision/<slug:slug>/', ajax_ver_revision, name='ajax_ver_Revision'),
    path('buscar_activo/<slug:slug>/', buscar_activo, name='buscar_activo'),
    path('actualizar_ver_activo/<slug:slug>/<str:codigo>/', actualizar_activo, name='vactualizar_activo'),

    path('ComparacionActivo/<slug:slug>/', Comparacion.as_view(), name='comparacion_revision_activo'),

    path('RevisionActivoObservado/<slug:slug>/', Revision_ActivosObservados.as_view(), name='revision_activo_observado'),
    path('buscar_activo_observado/<slug:slug>/', buscar_activo_obs, name='buscar_activo_observado'),
    path('actualizar_activo_obs/<slug:slug>/<str:codigo>/', actualizar_activo_obs, name='vactualizar_activo_observado'),

]

scraf/users/urls.py
from django.urls import path
from users.views import ListaPersonal, RegistroPersonal, ActualizacionPersonal, ListaCambiosPersonal
from activos.views_b import CargaMasivaPersonalView

app_name = 'users'
urlpatterns = [
    path('listaPersonal/', ListaPersonal.as_view(), name='lista_personal'),
    path('RegistroPersonal/', RegistroPersonal.as_view(), name='registro_personal'),
    path('ActualizacionPersonal/<slug:slug>', ActualizacionPersonal.as_view(), name='actualizacion_personal'),
    path('linePersona/<slug:slug>', ListaCambiosPersonal.as_view(), name='line_personal'),
    path('CargaDatosPersonal/', CargaMasivaPersonalView.as_view(), name='carga_datos_personal'),

]

scraf/activos/views.py
import uuid

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, View, ListView, UpdateView, TemplateView

from activos.forms import R_Activo, R_Activo_responsable, A_Activo, ActivoForm, A_Activo, MantenimientoActivoForm
from activos.models import Activo, AuxiliarContable, Line_Activo, MantenimientoActivo, GrupoContable
from designacion.models import Activo_responsable, Line_Activo_Responsable
from revision.views import get_menu_context
from users.models import User, Personal


class ListaActivos(LoginRequiredMixin, ListView):
    model = Activo
    template_name = "lista/activo.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_menu_context(self.request))
        context["titulo"] = "LISTA DE ACTIVOS EN LA INSTITUCION"
        context["object_list"] = self.model.objects.all().order_by("id")
        usuario = self.request.user
        usuario_d = User.objects.get(username=usuario)
        context.update(get_menu_context(self.request))
        if usuario_d.g_Activos:
            context["entity_registro"] = reverse_lazy("activos:registro_activos", args=[])
            context["entity_registro_nom"] = "REGISTRAR NUEVO ACTIVO"
        return context

class RegistroActivo(LoginRequiredMixin, CreateView):
    model = Activo
    template_name = "RegistroActualizacion/activo.html"
    form_class = ActivoForm
    success_url = reverse_lazy("activos:lista_activos")

    def get_context_data(self, **kwargs):
        context = super(RegistroActivo, self).get_context_data(**kwargs)
        context.update(get_menu_context(self.request))
        slug = self.kwargs.get("slug")
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)

        context['grupos_contables'] = GrupoContable.objects.all()
        
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        context["titulo"] = "REGISTRO DEL ACTIVO"
        context["subtitulo_1"] = "REGISTRO DEL ACTIVO"
        context["accion"] = "REGISTRO"
        context["accion2"] = "VOLVER"
        context["accion2_url"] = reverse_lazy("activos:lista_activos")
        return context
    
    def post(self, request, *args, **kwargs):
        usuario = self.request.user
        form = self.form_class(request.POST)
        if form.is_valid():
            codigo = form.cleaned_data.get("codigo")
            form.save()
            activo = self.model.objects.get(codigo=codigo)
            personal = Personal.objects.get(user__username = usuario)
            Activo_responsable.objects.create(
                activo = activo,
                responsable = personal,
                piso_ubicacion = 'ALMACENES',
                oficina_ubicacion = 'ALMACEN',
            )

            Line_Activo.objects.create(
                activo = activo,
                creador = usuario,
                estadoActivo = activo.estadoActivo,
                estadoDesignacion = activo.estadoDesignacion,
                mantenimiento = activo.mantenimiento,
                observacion = "Registro del Activo de Forma Manual"
            )
        return HttpResponseRedirect(reverse("activos:lista_activos"))

def get_auxiliares_por_grupo(request):
    grupo_id = request.GET.get('grupo_id')
    search_term = request.GET.get('q', '')
    if not grupo_id:
        return JsonResponse([], safe=False)
    try:
        auxiliares = AuxiliarContable.objects.filter(grupocontable_id=grupo_id)
        if search_term:
            auxiliares = auxiliares.filter(nombre__icontains=search_term)
        data = []
        for auxiliar in auxiliares:
            data.append({
                'id': auxiliar.id,
                'text': auxiliar.nombre
            })
        
        return JsonResponse(data, safe=False)
        
    except Exception as e:
        return JsonResponse([], safe=False)

class LineActivo(LoginRequiredMixin, TemplateView):
    template_name = "lista/lineActivo.html"
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context.update(get_menu_context(self.request))
            codigo = self.kwargs.get("codigo")
            activo = Activo.objects.get(codigo=codigo)
            activo_line = Line_Activo.objects.filter(activo=activo)
            activo_responsable_line = Line_Activo_Responsable.objects.filter(slug=activo).order_by("-fecha_registro")
            mantenimiento = MantenimientoActivo.objects.filter(activo = activo).order_by("-fechaInicio")
            context["titulo"] = "INFORMACION DEL ACTIVO"
            context["subtitulo_1"] = "LINE MODIFICACION DATOS ACTIVOS"
            context["subtitulo_2"] = "LINE MODIFICACION DESIGNACIONES ACTIVOS"
            context["subtitulo_3"] = "LINE MANTENIMIENTO ACTIVOS"
            context["activo"] = activo
            context["line_actvo"] = activo_line
            context["activo_responsable_line"] = activo_responsable_line
            context["mantenimiento"] = mantenimiento

            return context

class VerActivo(LoginRequiredMixin, TemplateView):
    template_name = "Visualizar/activo.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_menu_context(self.request))
        slug = self.kwargs.get("codigo")
        activo = Activo.objects.get(codigo=slug)
        context["titulo"] = "INFORMACION DEL ACTIVO"
        context["activo"] = activo
        lugar = Activo_responsable.objects.filter(activo=activo)
        if lugar:
            lugar = lugar.first()
            context["responsable"] = lugar
        mantenimiento = MantenimientoActivo.objects.filter(activo=activo, estado = True)
        if mantenimiento:
            mantenimientos = mantenimiento.first()
            context["mantenimientos"] = mantenimientos
        return context    

#-----------------------------------------------------------------------------------------------------------------
# ------------------- actualizar datos activo y habilitar mantenimiento --------------------
# ----------------------------------------------------------------------------------------------------------------

def gestionar_activo(request, activo_codigo):
    activo = get_object_or_404(Activo, codigo=activo_codigo)
    try:
        mantenimiento_activo = MantenimientoActivo.objects.get(
            activo=activo, 
            estado=True 
        )
    except MantenimientoActivo.DoesNotExist:
        mantenimiento_activo = None    
    if request.method == 'POST':
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':            
            if request.POST.get('form_type') == 'form_activo':                
                form_activo = A_Activo(
                    request.POST, 
                    instance=activo
                )
                if form_activo.is_valid():
                    instancia = form_activo.save()
                    activo = Activo.objects.get(codigo=instancia.codigo)
                    Line_Activo.objects.create(
                        activo = activo,
                        creador = request.user,
                        estadoActivo = activo.estadoActivo,
                        estadoDesignacion = activo.estadoDesignacion,
                        mantenimiento = activo.mantenimiento,
                        observacion = "Cambio de Estado"
                    )
                    return JsonResponse({
                        'success': True, 
                        'message': 'Estado del activo actualizado correctamente',
                        'codigo': instancia.codigo,
                    })
                else:
                    return JsonResponse({
                        'success': False, 
                        'errors': form_activo.errors
                    })
            
            elif request.POST.get('form_type') == 'form_mantenimiento':
                if request.POST.get('accion') == 'iniciar':
                    form_mantenimiento = MantenimientoActivoForm(request.POST)
                    if form_mantenimiento.is_valid():
                        instancia = form_mantenimiento.save(commit=False)
                        instancia.activo = activo
                        instancia.estado = True  # Activo
                        instancia.fechaInicio = timezone.now().date()
                        try:
                            personal_usuario = Personal.objects.get(user=request.user)
                            instancia.asignadorInicio = personal_usuario
                        except Personal.DoesNotExist:
                            return JsonResponse({
                                    'success': False, 
                                    'errors': {'general': 'El usuario no tiene un perfil de Personal asociado'}
                                })
                        instancia.save()
                        
                        activo.mantenimiento = True
                        activo.save()
                        Line_Activo.objects.create(
                            activo = activo,
                            creador = request.user,
                            estadoActivo = activo.estadoActivo,
                            estadoDesignacion = activo.estadoDesignacion,
                            mantenimiento = activo.mantenimiento,
                            observacion = "Inicio de Mantenimiento"

scraf/templates/lista/AuxiliaresContables.html
{% extends 'base/baseListasDatos.html' %}
{% load static %}
{% block thead %}
    <tr>
        <th scope="col">ID</th>
        <th scope="col">NOMBRE</th>
        <th scope="col">GRUPO</th>
    </tr>

{% endblock %}
{% block tbody %}
    {% for activo in object_list %}
        <tr>
            <td> {{ activo.id }}</td>
            <td> {{ activo.nombre }} </td>
            <td> {{ activo.grupocontable.nombre }} </td>
        </tr>
    {% endfor %}
{% endblock %}

scraf/templates/lista/GrupoContable.html
{% extends 'base/baseListasDatos.html' %}
{% load static %}
{% block thead %}
    <tr>
        <th scope="col">ID</th>
        <th scope="col">NOMBRE</th>
        <th scope="col">VER AUXILIARES</th>
    </tr>

{% endblock %}
{% block tbody %}
    {% for activo in object_list %}
        <tr>
            <td> {{ activo.id }}</td>
            <td> {{ activo.nombre }} </td>
            <td>
                <a href="{% url 'activos:ver_grupoAux' activo.id %} " type="button"
                   class="btn btn-primary btn-xs">
                   <i class="bi bi-eye"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

scraf/templates/lista/activo.html
{% extends 'base/baseListasDatos.html' %}
{% load static %}
{% block thead %}
    <tr>
        {% if user.g_Activos or user.v_Activos %}
        <th scope="col">LINE</th>
        {% endif %}        
        <th scope="col">CODIGO </br><small><i class="fa-solid fa-stop text-warning"></i> En Mantenimiento</br> <i class="fa-solid fa-stop text-success"></i> Asignado</br><i class="fa-solid fa-stop text-secondary"></i> Sin Asignar</small></th>
        <th scope="col">DESCRIPCION</th>
        <th scope="col">VER</th>
        {% if user.g_Activos %}
            <th scope="col">MODIFICAR</th>
        {% endif %}        
    </tr>
{% endblock %}
{% block tbody %}
    {% for activo in object_list %}
        <tr>
        {% if user.g_Activos or user.v_Activos %}
            <td>
                    <a href='{% url "activos:lista_lineactivo" activo.codigo %}' type="button"
                    class="btn btn-primary btn-xs">
                    <i class="bi bi-eye"></i>
                    </a>
                </td>
        {% endif %}
            
            <td class="{% if activo.mantenimiento %} table-warning {% elif activo.estadoDesignacion %} table-success {% endif %}"> {{ activo.codigo }} </td>
            <td> {{ activo.descActivo }}</td>
            <td>
                <a href="{% url 'activos:ver_activo' activo.codigo %}" type="button"
                   class="btn btn-primary btn-xs">
                   <i class="bi bi-eye"></i>
                </a>
            </td>
            {% if user.g_Activos %}
            <td>
                <a href="{% url 'activos:gestionar_activo' activo.codigo %} " type="button"
                   class="btn btn-primary btn-xs">
                   <i class="bi bi-brush-fill"></i>
                </a>
            </td>
        {% endif %}  
        </tr>
    {% endfor %}
{% endblock %}

scraf/templates/lista/activo_revision.html
{% extends 'base/baseListasDatos.html' %}
{% load static %}
{% block thead %}
    <tr>
        <th scope="col">SLUG</th>
        <th scope="col">CODIGO</th>
        <th scope="col">DESCRIPCION</th>
        <th scope="col">UBICACION OFICINA</th>
        <th scope="col">RESPONSABLE ACTUAL</th>
        <th scope="col">ESTADO</th>    
    </tr>

{% endblock %}
{% block tbody %}
    {% for activo in object_list %}
        <tr>
            <td> {{ activo.slug }}</td>
            <td> {{ activo.activo.codigo }} </td>
            <td> {{ activo.activo.descActivo }}</td>
            <td> {{ activo.oficina_ubicacion }}</td>
            <td> {{ activo.responsable }}</td>
            <td>
                <a href=" {% url 'activos:ver_activos_responsable' activo.slug %} " type="button"
                   class="btn btn-primary btn-xs">
                   <i class="fas fa-edit"></i> 
                </a>
            </td>
            {% if user.g_Activos %}
            <td>
                <a href=" {% url 'activos:actualizar_activos_responsable' activo.slug %} " type="button"
                   class="btn btn-primary btn-xs">
                   <i class="fas fa-edit"></i> 
                </a>
            </td>
        {% endif %}  
        </tr>
    {% endfor %}
{% endblock %}

scraf/templates/lista/asignaciones.html
{% extends 'base/baseListasDatos.html' %}
{% load static %}
{% block thead %}
    <tr>
        {% if user.g_Activos or user.v_Activos %}
        <th scope="col">LINE</th>
        {% endif %}    
        <th scope="col">ESTADO</th>
        <th scope="col">CODIGO ASIGNACION</th>
        <th scope="col">CARNET DEL RESPONSABLE</th>
        <th scope="col">CARGO DEL RESPONSABLE</th>
        <th scope="col">VER ACTIVOS ASIGNADOS</th>
        <th scope="col">VER DEVOLUCIONES</th>
    </tr>
{% endblock %}
{% block tbody %}
    {% for activo in object_list %}
        <tr>
        {% if user.g_Activos or user.v_Activos %}
        <td><a href="{% url 'designacion:line_asignaciones' activo.slug %}"><i class="fas fa-eye"></i></a></td>
        {% endif %}    
            
            {% if activo.estado %}<td class="table-success"> ACTIVO{% else %}<td>FINALIZADO{% endif %}</td>
            <td> {{ activo.slug }}</td>
            <td> {{ activo.carnet }}</td>
            <td> {{ activo.cargo }}</td>
            <td>
                <a href="{% url 'designacion:ver_asignaciones' activo.slug %}" type="button"
                   class="btn btn-primary btn-xs">
                   <i class="bi bi-eye"></i>
                </a>
            </td>
            <td>
                <a href="{% url 'designacion:ver_devolucion' activo.slug %}" type="button"
                   class="btn btn-primary btn-xs">
                   <i class="bi bi-eye"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

scraf/templates/lista/comparacionRevision.html
{% extends 'base/baseListasDatos.html' %}
{% load static %}
{% block thead %}
    <tr>
        <th scope="col">CODIGO</th>
        <th scope="col">DESCRIPCION</th>
        <th scope="col">ESTADO</th>
        <th scope="col">FECHA DE REVISION</th>
        <th scope="col">RESPONSABLE DE LA REVISION</th>
        <th scope="col">OBSERVACION</th>
    </tr>

{% endblock %}
{% block tbody %}
    {% for comparacion in comparaciones %}
        <tr>
            <td> {{ comparacion.0 }}</td>
            <td> {{ comparacion.1 }} </td>
            <td> {{ comparacion.2 }} </td>
            <td> {{ comparacion.3 }} </td>
            <td> {{ comparacion.4 }} </td>
            <td> {{ comparacion.5 }} 
                {% if comparacion.6 %}
                <a href="{% url 'revision:revision_activo_observado' slug %}"> <i class="fa-solid fa-pen"></i> <span>IR</span></a> 
                {% else %}
                {% endif %}
            </td>
        </tr>
    {% endfor %}
{% endblock %}

scraf/templates/lista/line_asignaciones.html
{% extends 'base/baseListasDatos.html' %}
{% load static %}
{% block thead %}
    <tr>
        <th scope="col">FECHA DE REGISTRO</th>
        <th scope="col">ESTADO</th>
        <th scope="col">USUARIO REGISTRO</th>
        <th scope="col">OBSERVACION</th>
    </tr>

{% endblock %}
{% block tbody %}
    {% for activo in object_list %}
        <tr>
            <td> {{ activo.fecha_registro }} </td>
            <td> {{ activo.estado }}</td>
            <td> {{ activo.creador }}</td>
            <td> {{ activo.observacion }}</td>
        </tr>
    {% endfor %}
{% endblock %}

scraf/templates/lista/personal.html
{% extends 'base/baseListasDatos.html' %}
{% load static %}
{% block thead %}
    <tr>
        <th scope="col">LINE</th>
        <th scope="col">ASIGNACIONES DEVOLUCIONES</th>
        <th scope="col">NOMBRE</th>
        <th scope="col">APELLIDO</th>
        <th scope="col">CARGO</th>
        <th scope="col">CARNET</th>
        <th scope="col">ULTIMA HORA DE CONEXION</th>
        <th scope="col">VER/EDITAR</th>
    </tr>

{% endblock %}
{% block tbody %}
    {% for personal in object_list %}
        <tr>
            <td><a href="{% url 'users:line_personal' personal.slug %}"><i class="fas fa-eye"></i></a></td>
            <td><a href="{% url 'designacion:lista_asignaciones_personaL' personal.persona.carnet %}"><i class="fas fa-eye"></i></a></td>
            <td> {{ personal.persona.nombre }}</td>
            <td> {{ personal.persona.apellido }} </td>
            <td> {{ personal.persona.cargo }}</td>
            <td> {{ personal.persona.carnet }}</td>
            <td> {{ personal.user.last_login }}</td>
            <td>
                <a href=" {% url 'users:actualizacion_personal' personal.slug %} " type="button"
                   class="btn btn-primary btn-xs">
                   <i class="fas fa-edit"></i> 
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

scraf/templates/lista/personal_line.html
{% extends 'base/baseListasDatos.html' %}
{% load static %}
{% block thead %}
    <tr>
        <th scope="col">FECHA DE REGISTRO</th>
        <th scope="col">RESPONSABLE DEL REGISTRO</th>
        <th scope="col">OBSERVACION</th>
    </tr>

{% endblock %}
{% block tbody %}
    {% for object in object_list %}
        <tr>
            <td> {{ object.fechaRegistro }} </td>
            <td> {{ object.encargado }}</td>
            <td class="text-start"> {{ object.observacion|linebreaks }}</td>
        </tr>
    {% endfor %}
{% endblock %}

scraf/templates/lista/verAsignaciones.html
{% extends 'base/base2card.html' %}
{% load static %}
{% block card1 %}
<div class="row">
    <div class="col-6">
        <label class="fw-bold">Nombre Completo</label>
        <input class="form-control" type="text" value="{{ persona.nombrecompleto }}" disabled readonly>
    </div>
    <div class="col-6">
        <label class="fw-bold">Cargo</label>
        <input class="form-control" type="text" value="{{ asignacion.cargo }}" disabled readonly>
    </div>
    <div class="col-4">
        <label class="fw-bold">Carnet</label>
        <input class="form-control" type="text" value="{{ persona.carnet }}" disabled readonly>
    </div>
    <div class="col-4">
        <label class="fw-bold">Contacto</label>
        <input class="form-control" type="text" value="{{ persona.contacto }}" disabled readonly>
    </div>
    <div class="col-4">
        <label class="fw-bold">Mosca</label>
        <input class="form-control" type="text" value="{{ persona.rubrica }}" disabled readonly>
    </div>
</div>
{% endblock  %}

{% block card2 %}
<div class="row mb-3">
    <div class="col-6">
        <label class="fw-bold">Fecha de Asignacion:</label>
        <input class="form-control" type="text" value="{{ asignacion.fecha_asignacion }}" disabled readonly>
    </div>
    <div class="col-6">
        <label class="fw-bold">Estado</label>
        {% if asignacion.estado %}
         <input class="form-control bg-success text-white" type="text" value="Asignado" disabled readonly>
        {% else %}
         <input class="form-control bg-primary" type="text" value="Devuelto" disabled readonly>
        {% endif %}       
    </div>
</div>
<div class="row">
    <div class="card-header bg-primary text-white">
        <h5 class="card-title mb-0">
            <div class="row align-items-center">
                <div class="col-auto"><i class="fa-solid fa-layer-group"></i></div>
                <div class="col">Cantidad de Activos Asignados: {{cantidad}}</div>
            </div>
        </h5>
    </div>
    <div class="row mt-3">
    {% for activo in activos  %}
    <a href="{% url 'activos:ver_activo' activo.codigo %}" type="button">
        <div class="border border-3 rounded mt-2">
            <b>{{ activo.codigo }}</b>  {{ activo.descActivo }}            
        </div>
    </a>
    {% endfor %}
    </div>
    
</div>
{% endblock  %}